### 1. 로그인
POST http://localhost/login
Content-Type: application/json

{
  "id": "admin",
  "pw": "pass"
}

### 2. 로그인 인증(토큰 인증)
POST http://localhost/check
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicHciOiJwYXNzIiwiaWF0IjoxNzg3ODk5MzQwLCJleHAiOjE3ODc5MDExNDB9.SCAJt1f_dA47-3Ki65Me2Hy-dJlpRHya2pm8DBjDW_w